<a href="https://colab.research.google.com/github/nancyngh13-debug/ciencia-de-datos/blob/aprendiendoPython/numpy_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

importar libreria numpy

In [17]:
import numpy as np

array = np.array([10,20,30,40, 50])
print (array[1])
print(array[-1])

20
50


In [4]:
print(array[1:4])

[20 30 40]


In [5]:
array = np.array([10,20,30,40, 50])
bool_index = array > 25
print(bool_index)
print(type[bool_index])

[False False  True  True  True]
type[array([False, False,  True,  True,  True])]


In [6]:
index = [2,3,4]
print(array[index])

[30 40 50]


sacar array aleatorio y representar en matriz de 3*3

In [7]:
array = np.random.randint(1,10, size=(3,3))
print(array)
print(array[0,1])

[[3 8 5]
 [4 9 9]
 [6 9 6]]
8


partir y mostrar una parte de la matriz

In [8]:
print(array[:2,:2])

[[3 8]
 [4 9]]


broadcasting

n NumPy, el broadcasting es una técnica que permite realizar operaciones aritméticas entre arrays de diferentes formas (shapes) sin necesidad de copiarlos o usar bucles explícitos.

Básicamente, NumPy "extiende" (o difunde) automáticamente el array más pequeño para que tenga una forma compatible con el más grande, siguiendo ciertas reglas, y luego aplica la operación elemento a elemento.

🔹 Reglas de Broadcasting
Cuando NumPy compara las dimensiones de dos arrays:

Se alinean las dimensiones desde el final (derecha a izquierda).
En cada dimensión:
Si son iguales, son compatibles.
Si una de ellas es 1, se "estira" para coincidir con la otra.
Si son diferentes y ninguna es 1, no son compatibles y se produce un error.
🔹 Ejemplo básico
Python

Copiar código
import numpy as np

# Array 1D
a = np.array([1, 2, 3])

# Escalar
b = 2

# Broadcasting: b se "expande" para coincidir con a
result = a * b
print(result)  # [2 4 6]


añadir descuento a todos los elementos del array y imprimir


In [9]:
prices = np.array([100,200,300])
discount = np.array([0.9])
discount_prices = prices * discount
print(discount_prices)

[ 90. 180. 270.]


In [10]:
prices = np.random.randint(100,500, size=(3,3))
discount = np.array([10,20,30])
discount_prices = prices + discount
print(prices)
print(discount_prices)


[[462 386 148]
 [328 476 124]
 [352 411 178]]
[[472 406 178]
 [338 496 154]
 [362 431 208]]


In [11]:
prices = np.array([200,300,400,500])
discount = np.array([20,30,40,50])
discount_prices = prices * discount
print(prices)
print(discount_prices)

[200 300 400 500]
[ 4000  9000 16000 25000]


all todos los elementos, any algun elemento


In [12]:
array = np.array([1,2,3,4,5])
print(np.all(array > 0))
print(np.any(array > 4))

True
True


concatenano array a con array b


In [13]:
array_a = np.array([1,2,3])
array_b = np.array([4,5,6])
concatenated_a = np.concatenate([array_a, array_a])
concatenated_ab = np.concatenate([array_a, array_b])
print(concatenated_a)
print(concatenated_ab)

[1 2 3 1 2 3]
[1 2 3 4 5 6]


stacking en numpy se refiere a apilar o combinar arrays alo de un nuevo eje o de un eje existente np.satck
Crea un nuevo eje y apila arrays a lo largo de él.

staked veritcal

In [14]:
stacked_v = np.vstack([array_a, array_b])
print(stacked_v)

[[1 2 3]
 [4 5 6]]


staked horizontal

In [19]:
stacked_h = np.hstack([array_a, array_b])
print(stacked_h)

[1 2 3 4 5 6]


la función numpy.split() se utiliza para dividir un arreglo (array) en subarreglos alo largo de un eje especifico sintaxis numpy.split(ary, indices_or_sections, axis=0)


In [20]:
array_c = np.arange(1,10)
split_array = np.split(array,3)
print(array)
print(split_array)

ValueError: array split does not result in an equal division