<a href="https://colab.research.google.com/github/nancyngh13-debug/ciencia-de-datos/blob/aprendiendoPython/Regresi%C3%B3n_lineal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Nancy gallego 05/06/2026 Ciencia de datos desde cero

matrices con numpy

-Potente para estructurar datos, implementar matrices multidimencionales, estas estructuras garantizan calculos eficientes con matrices

In [ ]:
#matriz unidimencional
import numpy as np
a=np.array([1,2,3])
print("1d array:")
print(a)
print()
#matriz bidimencional
b:np.array([(4,5,6),(7,8,9)])
print("2d array")
print(b)
print()


1d array:
[1 2 3]

2d array
[[2 3 4]
 [5 6 7]]



Evaluación eficiencia listas de python vs matrices numpy

In [ ]:
import sys
S= range (1000)
print("Resultado lista de python")
print(sys.getsizeof(5)*len(S))
print()

D=np.arange(1000)
print("Resultado lista de numpy")
print(D.size*D.itemsize)


Resultado lista de python
28000

Resultado lista de numpy
8000


In [ ]:
import time
SIZE =100000

L1= range(SIZE)
L2= range(SIZE)
A1=np.arange(SIZE)
A2=np.arange(SIZE)

start=time.time()
Result=[(x,y) for x,y in zip(L1,L2)]
print("Resultado Lista python:")
print((time.time()-start)*1000)
print()

start=time.time()
Result=A1+A2
print("Resultado Numpy array:")
print((time.time()-start)*1000)

Resultado Lista python:
89.44225311279297

Resultado Numpy array:
34.11602973937988


In [ ]:
#Crear una matriz de unas -3 filas y 4 columnas
unos = np.ones((3,4))
print(unos)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#Crear una matriz de ceros - 3 filas 4 columnas
ceros = np.zeros((3,4))
print(ceros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
#Crear una matriz con valores aleatorios
aleatorios =np.random.random ((2,2))
print(aleatorios)


[[0.46556622 0.13523154]
 [0.72839797 0.98440917]]


In [ ]:
#Crear matriz vacia
vacia = np.empty((3,2))
print(vacia)


[[2.0e-323 2.5e-323]
 [3.0e-323 3.5e-323]
 [4.0e-323 4.4e-323]]


In [ ]:
#Crear una matriz con un solo valor
full = np.full((2,2),8)
print(full)

[[8 8]
 [8 8]]


In [ ]:
#crear una matriz con valores espaciados uniformemente
espacio1 = np.arange(0,30,5)
print(espacio1)
espacio2 = np.linspace(0,5,10)
print(espacio2)

[ 0  5 10 15 20 25]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [ ]:
#Crear una matriz identidad
identidad1 = np.eye(4,4)
print(identidad1)
identidad2 = np.identity(4)
print(identidad2)
#

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


inspeccionar matrices

In [ ]:
#Conocer las dimenciones de una matriz
a=np.array([(1,2,3),(4,5,6)])
print(a.ndim)

2


In [ ]:
#Consular el tipo de datos
a=np.array([(1,2,3)])
print(a.dtype)

int64


In [ ]:
#Consultar el tamaño y la forma de la matriz
a=np.array([(1,2,3,4,5,6)])
print(a.size)
print(a.shape)

6
(1, 6)


In [ ]:
#Cambio de forma de una matriz
a=np.array([(8,9,10),(11,12,13)])
print(a)
a=a.reshape(3,2)
print(a)
#

[[ 8  9 10]
 [11 12 13]]
[[ 8  9]
 [10 11]
 [12 13]]


In [ ]:
#Extraer un solo valor de la matriz - el valor ubicado en la fina 0 comumna 2
a = np.array([(1,2,3,4),(3,4,5,6)])
print(a[0,2])

3


In [ ]:
#Extraeer los valores de todas las filas ubicadas en la columna 3
a=np.array([(1,2,3,4),(3,4,5,6)])
print(a[0:,2])

[3 5]
