<a href="https://colab.research.google.com/github/nancyngh13-debug/ciencia-de-datos/blob/aprendiendoPython/Unique_Matriz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

importar libreria


In [2]:
import numpy as np

respuestas sugeridas


In [4]:
surgey_responses = np.array(["bueno", "excelente", "malo",
                             "bueno", "malo", "excelente",
                             "bueno", "bueno", "malo",
                             "excelente"])
print(np.unique(surgey_responses))

['bueno' 'excelente' 'malo']


imprimir valores unicos y contar cuantos de estos se tienen

In [5]:
unique_elements, counts = np.unique(surgey_responses, return_counts=True)
print(unique_elements)
print(counts)

['bueno' 'excelente' 'malo']
[4 3 3]


imprimir y modificaar vistas


In [12]:
x = np.arange(10)
vista = x[1:3]

print(x)
print(vista)

# Modificar la vista
x[1:3] = [10, 11]
print(x)
print(vista)

[0 1 2 3 4 5 6 7 8 9]
[1 2]
[ 0 10 11  3  4  5  6  7  8  9]
[10 11]


copias


In [15]:
array_x = np.arange(10)
copy_x = array_x[[1,2]]
print(array_x)
print(copy_x)

array_x[1:3] = [10, 11]
print(array_x)
print(copy_x)

[0 1 2 3 4 5 6 7 8 9]
[1 2]
[ 0 10 11  3  4  5  6  7  8  9]
[1 2]


Transformación de arrays

In [16]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
np.transposed_matrix = matrix.T
print(matrix)
print(np.transposed_matrix)
#

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


En Python, usando la librería NumPy, el término reshape se refiere a cambiar la forma (dimensiones) de un arreglo sin alterar sus datos.

La función principal es:

numpy.reshape(a, newshape)

In [19]:
array = np.arange(1,13)
reshaped_array = array.reshape(3,4)
print(array)
print(reshaped_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


En Python, reversed() es una función incorporada que invierte el orden de una secuencia estándar (listas, tuplas, cadenas, rangos, etc.), pero no está diseñada directamente para arreglos de NumPy.

En NumPy, si quieres invertir un arreglo, no usas reversed() directamente, sino técnicas específicas porque numpy.ndarray no implementa el protocolo de secuencia completo que reversed() requiere.

In [21]:
reversed_array = array[::-1]
print(array)
print(reversed_array)
#

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[12 11 10  9  8  7  6  5  4  3  2  1]


En NumPy, el término correcto es flatten() (no flatened), y es un método de los arreglos (ndarray) que devuelve una copia del arreglo convertido en una sola dimensión.

se usa mucho para aplanar imagenes en pixeles, para aplanar imagenes y que se puedan procesar a la hora de udar deep learning

In [22]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
flattened_array = matrix.flatten()
print(matrix)
print(flattened_array)
#

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


Ejercicio practico

In [28]:
import numpy as np
meses = np.array (["ENERO", "FEBRERO", "MARZO", "ABRIL", "MAYO", "JUNIO", "JULIO", "AGOSTO", "SEPTIEMBRE", "OCTUBRE", "NOVIEMBRE", "DICIEMBRE"])
productoA = np.array([150,200,250,300,220,210,180,190,230,240,280,300])
productoB = np.array([180,210,230,250,270,260,240,250,270,290,310,330])
productoC = np.array([200,220,240,260,280,300,320,340,360,380,400,420])
print("Total ventas a", productoA.sum())
print("Total ventas b", productoB.sum())
print("Total ventas c", productoC.sum())
print("Total media a", productoA.mean())
print("Total media  b", productoB.mean())
print("Total media c", productoC.mean())
ventas_totales = productoA + productoB + productoC

print("VENTAS TOTALES POR MES:")
print(ventas_totales)

for i in range(len(meses)):
    print(f"{meses[i]}: {ventas_totales[i]} unidades")

mesMayor = np.argmax(ventas_totales)
mesMenor = np.argmin(ventas_totales)
print(f"El mes con mayor ventas fue {meses[mesMayor]} con {ventas_totales[mesMayor]} unidades.")
print(f"El mes con menor ventas fue {meses[mesMenor]} con {ventas_totales[mesMenor]} unidades.")

matrizVentas = np.array([productoA, productoB, productoC])
matrizReshape = matrizVentas.reshape(3,4,3)
print(f"Matriz Tridimensional{matrizReshape}")
matrizTranspuesta = np.transpose(matrizVentas)
print(matrizTranspuesta)

print(productoA[::-1])
print(productoB[::-1])
print(productoC[::-1])

print(matrizReshape.flatten())

valoresUnicos, conteo = np.unique(ventas_totales, return_counts=True)
print("Valores Unicos", valoresUnicos)
print("Cuantas veces aparece cada uno:", conteo)

mesesPrimerTrimestre = meses[0:3]
ventasPrimerTrimestre = ventas_totales[0:3]
print(f"Meses{mesesPrimerTrimestre}")
print(f"Ventas{ventasPrimerTrimestre}")

indexacionBooleana = ventas_totales > 800
mesesMayores = meses[indexacionBooleana]
ventasMayores = ventas_totales[indexacionBooleana]

for i in range(len(mesesMayores)):
    print(f"{mesesMayores[i]}: {ventasMayores[i]} unidades")

indicePar = [1,3,5,7,9,11]
mesPar = meses[indicePar]
ventasPar = ventas_totales[indicePar]
matrizPar = np.array ([mesPar, ventasPar])
print(matrizPar)



Total ventas a 2750
Total ventas b 3090
Total ventas c 3720
Total media a 229.16666666666666
Total media  b 257.5
Total media c 310.0
VENTAS TOTALES POR MES:
[ 530  630  720  810  770  770  740  780  860  910  990 1050]
ENERO: 530 unidades
FEBRERO: 630 unidades
MARZO: 720 unidades
ABRIL: 810 unidades
MAYO: 770 unidades
JUNIO: 770 unidades
JULIO: 740 unidades
AGOSTO: 780 unidades
SEPTIEMBRE: 860 unidades
OCTUBRE: 910 unidades
NOVIEMBRE: 990 unidades
DICIEMBRE: 1050 unidades
El mes con mayor ventas fue DICIEMBRE con 1050 unidades.
El mes con menor ventas fue ENERO con 530 unidades.
Matriz Tridimensional[[[150 200 250]
  [300 220 210]
  [180 190 230]
  [240 280 300]]

 [[180 210 230]
  [250 270 260]
  [240 250 270]
  [290 310 330]]

 [[200 220 240]
  [260 280 300]
  [320 340 360]
  [380 400 420]]]
[[150 180 200]
 [200 210 220]
 [250 230 240]
 [300 250 260]
 [220 270 280]
 [210 260 300]
 [180 240 320]
 [190 250 340]
 [230 270 360]
 [240 290 380]
 [280 310 400]
 [300 330 420]]
[300 280 240 

In [27]:

# EJERCICIO 1 Crear datos de ventas de 3 productos en 12 meses

meses = np.array(['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'])

ventas_a = np.array ([50000,60000,30000,45000,70000,40000,38000,80000,90000,35000,44000,90000])
ventas_b = np.array ([6000,7000,4000,4000,7000,4000,3800,8000,9000,3500,4400,9000])
ventas_c = np.array ([150000,160000,130000,145000,170000,140000,108000,180000,90000,135000,144000,90000])

print("\n")

# SUMA DE VENTAS POR PRODUCTO
total_ventas_a = ventas_a.sum()
total_ventas_b = ventas_b.sum()
total_ventas_c = ventas_c.sum()
print("Total ventas producto a :\n", total_ventas_a)
print("Total ventas producto b :\n", total_ventas_b)
print("Total ventas producto c :\n", total_ventas_c)

# PROMEDIO MENSUAL POR PRODUCTO
promedio_a = ventas_a.mean()
promedio_b = ventas_b.mean()
promedio_c = ventas_c.mean()
print("Promedio producto a :\n", promedio_a)
print("Promedio producto b :\n",promedio_b)
print("Promedio producto c :\n",promedio_c)

print("\n")

# Manipulación Análisis de datos
#Total ventas por mes

total_ventas_mes = ventas_a + ventas_b + ventas_c
print("Total ventas por mes :\n", total_ventas_mes)

#Promedio por producto

promedio_producto = np.array([promedio_a, promedio_b, promedio_c])
print("Venta promedio por producto :\n", promedio_producto)

#VENTA MÁXIMA

venta_max = total_ventas_mes.max()
mes_max = meses[np.argmax(total_ventas_mes)]

print("Venta máxima:\n", mes_max, venta_max)

#VENTA MINIMA

venta_min = total_ventas_mes.min()
mes_min = meses[np.argmin(total_ventas_mes)]

print("Venta mínima:\n", mes_min, venta_min)

print("\n")

#OPERACIONES AVANZADAS
ventas = np.vstack ((ventas_a, ventas_b, ventas_c))
print("Matriz 2d:\n",ventas)

reshaped_ventas = ventas.reshape(3, 4, 3)
print("Reshaped:\n", reshaped_ventas)

print("\n")

#Trasponer

trasposed_matriz = ventas.T
print("Trasponer:\n", trasposed_matriz)

print("\n")

#Invertir

reversed_ventas = ventas[::-1]
print("Invertir:\n", reversed_ventas)

#Unidimensional

flattened_ventas = ventas.flatten()
print("Unidimensional :\n", flattened_ventas)

print("\n")

#CONTEO UNICO
elementos_unicos_ventas, counts = np.unique(ventas, return_counts=True)
print(elementos_unicos_ventas)
print(counts)

print("\n")

#INDEXAR Y SLICING
#VENTAS 1ER TRIMESTRE
num_mes = np.arange(1,13)
print(num_mes)

print(meses[num_mes<4])
print(total_ventas_mes[num_mes <4])

# Booleano ventas mayor a $200.000

mes_venta_mayor_dos = meses [total_ventas_mes>=200000]
venta_mayor_dos = total_ventas_mes[total_ventas_mes>=200000]
print("Mes con ventas superiores a $200.000 :\n", mes_venta_mayor_dos)
print("Total ventas mes :\n",venta_mayor_dos)

# Ventas pares

meses_pares = [1, 3, 5, 7, 9, 11]

ventas_mes_par = ventas [:, meses_pares]

print("ventas mes par:\n", ventas_mes_par)



Total ventas producto a :
 672000
Total ventas producto b :
 69700
Total ventas producto c :
 1642000
Promedio producto a :
 56000.0
Promedio producto b :
 5808.333333333333
Promedio producto c :
 136833.33333333334


Total ventas por mes :
 [206000 227000 164000 194000 247000 184000 149800 268000 189000 173500
 192400 189000]
Venta promedio por producto :
 [ 56000.           5808.33333333 136833.33333333]
Venta máxima:
 Agosto 268000
Venta mínima:
 Julio 149800


Matriz 2d:
 [[ 50000  60000  30000  45000  70000  40000  38000  80000  90000  35000
   44000  90000]
 [  6000   7000   4000   4000   7000   4000   3800   8000   9000   3500
    4400   9000]
 [150000 160000 130000 145000 170000 140000 108000 180000  90000 135000
  144000  90000]]
Reshaped:
 [[[ 50000  60000  30000]
  [ 45000  70000  40000]
  [ 38000  80000  90000]
  [ 35000  44000  90000]]

 [[  6000   7000   4000]
  [  4000   7000   4000]
  [  3800   8000   9000]
  [  3500   4400   9000]]

 [[150000 160000 130000]
  [145000

calculos Matriciales

suma de matrices

In [32]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
#Suma
sum =  A + B
print(sum)
print(A)
print(B)

[[ 6  8]
 [10 12]]
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [36]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
#resta
res =  A - B
print(res)
print(A)
print(B)

[[-4 -4]
 [-4 -4]]
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


resta

producto de las matrices
metododo dot


In [33]:
#multiplicación
product = np.dot(A,B)
print(product)

[[19 22]
 [43 50]]


encontrar la determinante y la inversa de una matriz

In [35]:
A = np.array([[1,2],[3,4]])
det_A = np.linalg.det(A)
inv_A = np.linalg.inv(A)
print(A)
print(det_A)
print(inv_A)
#

[[1 2]
 [3 4]]
-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]


In [37]:
#resolver Ax = b
b = np.array([5,6])
x = np.linalg.solve(A,b)
print(A)
print(b)
print(x)

[[1 2]
 [3 4]]
[5 6]
[-4.   4.5]


In [38]:
import numpy as np

array1 = np.array([10, 20, 30, 40])
array2 = np.array([1, 2, 3, 4])

suma = array1 + array2
resta = array1 - array2
multiplicacion = array1 * array2
division = array1 / array2

print("Suma:", suma)
print("Resta:", resta)
print("Multiplicación:", multiplicacion)
print("División:", division)

Suma: [11 22 33 44]
Resta: [ 9 18 27 36]
Multiplicación: [ 10  40  90 160]
División: [10. 10. 10. 10.]


In [39]:
datos = np.array([23, 76, 35, 67, 89, 45, 68, 79, 35])

media = np.mean(datos)
mediana = np.median(datos)
varianza = np.var(datos)
desviacion = np.std(datos)

print("Media:", media)
print("Mediana:", mediana)
print("Varianza:", varianza)
print("Desviación estándar:", desviacion)

Media: 57.44444444444444
Mediana: 67.0
Varianza: 484.02469135802465
Desviación estándar: 22.000561160071


In [40]:
matriz1 = np.array([[1, 2], [3, 4]])
matriz2 = np.array([[5, 6], [7, 8]])

suma_matrices = matriz1 + matriz2
resta_matrices = matriz1 - matriz2
producto_matrices = np.dot(matriz1, matriz2)
inversa_matriz1 = np.linalg.inv(matriz1)

print("Suma de matrices:\n", suma_matrices)
print("Resta de matrices:\n", resta_matrices)
print("Producto de matrices:\n", producto_matrices)
print("Inversa de la matriz 1:\n", inversa_matriz1)

Suma de matrices:
 [[ 6  8]
 [10 12]]
Resta de matrices:
 [[-4 -4]
 [-4 -4]]
Producto de matrices:
 [[19 22]
 [43 50]]
Inversa de la matriz 1:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [41]:

A = np.array([[2, 3], [1, 2]])
b = np.array([8, 5])

x = np.linalg.solve(A, b)
print("Solución del sistema de ecuaciones:", x)

Solución del sistema de ecuaciones: [1. 2.]


In [42]:
datos_simulados = np.random.normal(0, 1, 1000)
media_simulada = np.mean(datos_simulados)
desviacion_simulada = np.std(datos_simulados)

print("Media de los datos simulados:", media_simulada)
print("Desviación estándar de los datos simulados:", desviacion_simulada)

Media de los datos simulados: -0.01499565319617472
Desviación estándar de los datos simulados: 1.022915765583782
